// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alohaio.proto

#include "alohaio.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace alohaio {
class SystemCookieDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SystemCookie>
      _instance;
} _SystemCookie_default_instance_;
class UserCookieDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UserCookie>
      _instance;
} _UserCookie_default_instance_;
}  // namespace alohaio
namespace protobuf_alohaio_2eproto {
static void InitDefaultsSystemCookie() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::alohaio::_SystemCookie_default_instance_;
    new (ptr) ::alohaio::SystemCookie();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::alohaio::SystemCookie::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SystemCookie =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSystemCookie}, {}};

static void InitDefaultsUserCookie() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::alohaio::_UserCookie_default_instance_;
    new (ptr) ::alohaio::UserCookie();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::alohaio::UserCookie::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UserCookie =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUserCookie}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SystemCookie.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UserCookie.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::alohaio::SystemCookie, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::alohaio::SystemCookie, ret_code_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::alohaio::UserCookie, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::alohaio::SystemCookie)},
  { 6, -1, sizeof(::alohaio::UserCookie)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::alohaio::_SystemCookie_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::alohaio::_UserCookie_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "alohaio.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ralohaio.proto\022\007alohaio\" \n\014SystemCookie"
      "\022\020\n\010ret_code\030\001 \001(\005\"\014\n\nUserCookieb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 80);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "alohaio.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_alohaio_2eproto
namespace alohaio {

// ===================================================================

void SystemCookie::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SystemCookie::kRetCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SystemCookie::SystemCookie()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_alohaio_2eproto::scc_info_SystemCookie.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:alohaio.SystemCookie)
}
SystemCookie::SystemCookie(const SystemCookie& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ret_code_ = from.ret_code_;
  // @@protoc_insertion_point(copy_constructor:alohaio.SystemCookie)
}

void SystemCookie::SharedCtor() {
  ret_code_ = 0;
}

SystemCookie::~SystemCookie() {
  // @@protoc_insertion_point(destructor:alohaio.SystemCookie)
  SharedDtor();
}

void SystemCookie::SharedDtor() {
}

void SystemCookie::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SystemCookie::descriptor() {
  ::protobuf_alohaio_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_alohaio_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SystemCookie& SystemCookie::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_alohaio_2eproto::scc_info_SystemCookie.base);
  return *internal_default_instance();
}


void SystemCookie::Clear() {
// @@protoc_insertion_point(message_clear_start:alohaio.SystemCookie)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ret_code_ = 0;
  _internal_metadata_.Clear();
}

bool SystemCookie::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:alohaio.SystemCookie)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 ret_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ret_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:alohaio.SystemCookie)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:alohaio.SystemCookie)
  return false;
#undef DO_
}

void SystemCookie::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:alohaio.SystemCookie)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ret_code = 1;
  if (this->ret_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ret_code(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:alohaio.SystemCookie)
}

::google::protobuf::uint8* SystemCookie::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:alohaio.SystemCookie)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ret_code = 1;
  if (this->ret_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->ret_code(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:alohaio.SystemCookie)
  return target;
}

size_t SystemCookie::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:alohaio.SystemCookie)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 ret_code = 1;
  if (this->ret_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ret_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SystemCookie::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:alohaio.SystemCookie)
  GOOGLE_DCHECK_NE(&from, this);
  const SystemCookie* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SystemCookie>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:alohaio.SystemCookie)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:alohaio.SystemCookie)
    MergeFrom(*source);
  }
}

void SystemCookie::MergeFrom(const SystemCookie& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:alohaio.SystemCookie)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ret_code() != 0) {
    set_ret_code(from.ret_code());
  }
}

void SystemCookie::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:alohaio.SystemCookie)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SystemCookie::CopyFrom(const SystemCookie& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:alohaio.SystemCookie)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SystemCookie::IsInitialized() const {
  return true;
}

void SystemCookie::Swap(SystemCookie* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SystemCookie::InternalSwap(SystemCookie* other) {
  using std::swap;
  swap(ret_code_, other->ret_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SystemCookie::GetMetadata() const {
  protobuf_alohaio_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_alohaio_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UserCookie::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserCookie::UserCookie()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_alohaio_2eproto::scc_info_UserCookie.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:alohaio.UserCookie)
}
UserCookie::UserCookie(const UserCookie& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:alohaio.UserCookie)
}

void UserCookie::SharedCtor() {
}

UserCookie::~UserCookie() {
  // @@protoc_insertion_point(destructor:alohaio.UserCookie)
  SharedDtor();
}

void UserCookie::SharedDtor() {
}

void UserCookie::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UserCookie::descriptor() {
  ::protobuf_alohaio_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_alohaio_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UserCookie& UserCookie::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_alohaio_2eproto::scc_info_UserCookie.base);
  return *internal_default_instance();
}


void UserCookie::Clear() {
// @@protoc_insertion_point(message_clear_start:alohaio.UserCookie)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool UserCookie::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:alohaio.UserCookie)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:alohaio.UserCookie)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:alohaio.UserCookie)
  return false;
#undef DO_
}

void UserCookie::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:alohaio.UserCookie)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:alohaio.UserCookie)
}

::google::protobuf::uint8* UserCookie::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:alohaio.UserCookie)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:alohaio.UserCookie)
  return target;
}

size_t UserCookie::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:alohaio.UserCookie)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UserCookie::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:alohaio.UserCookie)
  GOOGLE_DCHECK_NE(&from, this);
  const UserCookie* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UserCookie>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:alohaio.UserCookie)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:alohaio.UserCookie)
    MergeFrom(*source);
  }
}

void UserCookie::MergeFrom(const UserCookie& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:alohaio.UserCookie)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void UserCookie::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:alohaio.UserCookie)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserCookie::CopyFrom(const UserCookie& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:alohaio.UserCookie)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserCookie::IsInitialized() const {
  return true;
}

void UserCookie::Swap(UserCookie* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserCookie::InternalSwap(UserCookie* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UserCookie::GetMetadata() const {
  protobuf_alohaio_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_alohaio_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace alohaio
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::alohaio::SystemCookie* Arena::CreateMaybeMessage< ::alohaio::SystemCookie >(Arena* arena) {
  return Arena::CreateInternal< ::alohaio::SystemCookie >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::alohaio::UserCookie* Arena::CreateMaybeMessage< ::alohaio::UserCookie >(Arena* arena) {
  return Arena::CreateInternal< ::alohaio::UserCookie >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
